# tasks file for ansible-role-cfn-elb
- name: Create build directory
  file:
    dest: build
    state: directory

- name: Template role
  template:
    src: elb.j2
    dest: "build/elb.json"

- name: Create or remove role stack
  cloudformation:
    template: "build/elb.json"
    stack_name: "{{ elb_role_stack_name }}"
    state: "{{ elb_role_stack_state|default('present') }}"
    region: "{{ region|default('us-west-2') }}"
    security_token: "{{ lookup('env','AWS_SESSION_TOKEN')|default(omit, true) }}"
    tags: "{{ elb_tags }}"
    template_format: yaml
